# Setup selenoid grid locally (https://github.com/aerokube/selenoid)
# Uses browsers.json to setup capability, available in project root path
# $ docker pull selenoid/vnc_chrome:73.0
# $ docker pull selenoid/vnc_firefox:66.0
# $ docker-compose -f docker-compose-selenoid.yml -p selenoid up -d

# In testsetup, include capability as:
#
#   capabilities = {
#    "browserName": "firefox",
#    "version": "66.0",
#    "enableVNC": True,
#    "enableVideo": False
#   }

# Can view VNC videos on http://localhost:8080
# The selenium grid is available at http://127.0.0.1:4444/wd/hub

version: '2.1'
services:
  selenoid:
    hostname: selenoid
    container_name: selenoid
    tty: true
    privileged: true
    network_mode: bridge
    image: aerokube/selenoid:latest
    volumes:
      - "./:/etc/selenoid:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: ["-limit", "10", "-log-output-dir", "/opt/selenoid/logs"]
    ports:
      - "4444:4444"
    environment:
      - TZ=Pacific/Auckland

  selenoid-ui:
    hostname: selenoid-ui
    container_name: selenoid-ui
    image: aerokube/selenoid-ui
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
